In [1]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

df = pd.read_excel('customer_churn.xlsx')
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [13]:
df.columns = df.columns.str.strip()

In [14]:
df.isnull().sum()

CustomerID           0
Count                0
Country              0
State                0
City                 0
Zip Code             0
Lat Long             0
Latitude             0
Longitude            0
Gender               0
Senior Citizen       0
Partner              0
Dependents           0
Tenure Months        0
Phone Service        0
Multiple Lines       0
Internet Service     0
Online Security      0
Online Backup        0
Device Protection    0
Tech Support         0
Streaming TV         0
Streaming Movies     0
Contract             0
Paperless Billing    0
Payment Method       0
Monthly Charges      0
Total Charges        0
Churn Label          0
Churn Value          0
Churn Score          0
CLTV                 0
Churn Reason         0
dtype: int64

In [15]:
df['Total Charges'] = pd.to_numeric(df['Total Charges'], errors='coerce')

In [16]:
df = df[df['Total Charges'].notnull()]

In [17]:
df['Churn Value']

0       1
1       1
2       1
3       1
4       1
       ..
1864    1
1865    1
1866    1
1867    1
1868    1
Name: Churn Value, Length: 1869, dtype: int64

In [18]:
df.drop(['CustomerID', 'Count', 'Lat Long'], axis=1, inplace=True)

In [19]:
yes_no_cols = ['Partner', 'Dependents', 'Phone Service', 'Paperless Billing']

for col in yes_no_cols:
    df[col] = df[col].map({'Yes':1, 'No':0})

In [20]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 1869 entries, 0 to 1868
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country            1869 non-null   object
 1   State              1869 non-null   object
 2   City               1869 non-null   object
 3   Zip Code           1869 non-null   int64
 4   Latitude           1869 non-null   float64
 5   Longitude          1869 non-null   float64
 6   Gender             1869 non-null   object
 7   Senior Citizen     1869 non-null   object
 8   Partner            1869 non-null   int64
 9   Dependents         1869 non-null   int64
 10  Tenure Months      1869 non-null   int64
 11  Phone Service      1869 non-null   int64
 12  Multiple Lines     1869 non-null   object
 13  Internet Service   1869 non-null   object
 14  Online Security    1869 non-null   object
 15  Online Backup      1869 non-null   object
 16  Device Protection  1869 non-null   object
 17  Tech Support       1869 non-null   object
 18  Streaming TV       1869 non-null   object
 19  Streaming Movies   1869 non-null   object
 20  Contract           1869 non-null   object
 21  Paperless Billing  1869 non-null   int64
 22  Payment Method     1869 non-null   object
 23  Monthly Charges    1869 non-null   float64
 24  Total Charges      1869 non-null   float64
 25  Churn Label        1869 non-null   object
 26  Churn Value        1869 non-null   int64
 27  Churn Score        1869 non-null   int64
 28  CLTV               1869 non-null   int64
 29  Churn Reason       1869 non-null   object
dtypes: float64(4), int64(9), object(17)
memory usage: 452.6+ KB

,Country,State,City,Zip Code,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,United States,California,Los Angeles,90003,33.964131,-118.272783,Male,No,0,0,...,Month-to-month,1,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,United States,California,Los Angeles,90005,34.059281,-118.307420,Female,No,0,1,...,Month-to-month,1,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,United States,California,Los Angeles,90006,34.048013,-118.293953,Female,No,0,1,...,Month-to-month,1,Electronic check,99.65,820.50,Yes,1,86,5372,Moved
3,United States,California,Los Angeles,90010,34.062125,-118.315709,Female,No,1,1,...,Month-to-month,1,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,United States,California,Los Angeles,90015,34.039224,-118.266293,Male,No,0,1,...,Month-to-month,1,Bank transfer (automatic),103.70,5036.30,Yes,1,89,5340,Competitor had better devices

In [21]:
df['Churn Value'].value_counts(normalize=True) * 100

Churn Value
1    100.0
Name: proportion, dtype: float64

In [22]:
pd.crosstab(df['Contract'], df['Churn Value'], normalize='index') * 100

Churn Value         1
Contract
Month-to-month  100.0
One year        100.0
Two year        100.0

In [23]:
pd.crosstab(df['Internet Service'], df['Churn Value'], normalize='index') * 100

Churn Value           1
Internet Service
DSL               100.0
Fiber optic       100.0
No                100.0

In [24]:
df.groupby('Churn Value')['Monthly Charges'].mean()

Churn Value
1    74.441332
Name: Monthly Charges, dtype: float64

In [25]:
df.groupby('Churn Value')['Tenure Months'].mean()

Churn Value
1    17.979133
Name: Tenure Months, dtype: float64

In [26]:
pd.crosstab(df['Payment Method'], df['Churn Value'], normalize='index') * 100

Churn Value                    1
Payment Method
Bank transfer (automatic)  100.0
Credit card (automatic)    100.0
Electronic check           100.0
Mailed check               100.0

 Example Insights:
.Customers with month-to-month contracts have the highest churn
.Customers with higher monthly charges are more likely to leave
.Customers with short tenure are at high risk
.Certain payment methods show higher churn